name: health_passport
description: "A new Flutter project."

publish_to: 'none' # Not publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  http: ^1.2.2
  provider: ^6.1.2
  percent_indicator: ^4.2.4
  curved_navigation_bar: ^1.0.3
  fl_chart: ^0.70.2
  font_awesome_flutter: ^10.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mumbai_diet.xlsx
    - assets/washington_diet.xlsx
    - assets/capetown_diet.xlsx
    - assets/App_logo2.png
    - assets/bckgrnd2.jpg
    - assets/amazon.png
    # - assets/bckgrnd_img.png
    #- assets/earth_logo.jpg
    #- assets/travel_icon.jpg
    # - assets/bckgrnd3.jpg
    #- assets/bckgrnd2.jpg
    # - assets/bckgrnd1.jpg


# Specify the Android package name to match the manifest.
android:
  package: travelshield.com

# Optional: You can add flutter_launcher_icons if you need an app icon:
# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/icon/app_icon.png"